
project_id = "gkjgrmnvfmlhinxordtz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions.slack-notify]
verify_jwt = false

[functions.email-notify]
verify_jwt = false

[functions.auto-respond-asset]
verify_jwt = false

[functions.hr-chat]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.send-verification]
verify_jwt = false

[functions.verify-token]
verify_jwt = false
