
project_id = "ymdlgdvjfgqbpyawurnu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions.slack-notify]
verify_jwt = false

[functions.email-notify]
verify_jwt = false

[functions.hr-chat]
verify_jwt = false
